encoder_params:
  input_dim: 80
  num_heads: 16 #prev 16
  encoder_dim: 1024 #prev 1024
  num_layers: 12 #prev 12
  feed_forward_expansion_factor: 4
  conv_expansion_factor: 2
  conv_kernel_size: 31
  dropout: 0.1

feature_params:
  n_mels: 80
  sample_rate: 16s000
  win_length: 960

rq_params:
  n_mels: 80
  codebook_size: 1000
  codebook_dim: 512

mask_params:
  mask_prob: 0.15
  mask_length: 4
  mask_value: 0.0

train_params:
  max_steps: 100000
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-5



